### PR TITLE
Fixes #103, #102, and #85

### LINKED ISSUE #103: using ember-cli-yadda with ember-cli-blanket 'Error: Could not find module yadda'
We have installed the latest versions of ember-cli-yadda and ember-cli-blanket, with ember-cli 1.13.8.  When running /tests without blanket coverage the BDD tests run fine.  When running /tests?coverage to enable blanket coverage, the BDD tests fail with:
```
Died on test #1     at Object.TestLoader.moduleLoadFailure (http://localhost:4200/assets/test-support.js:5854:11)
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:31:14)
    at Object.TestLoader.loadModules (http://localhost:4200/assets/test-loader.js:21:18)
    at Function.TestLoader.load (http://localhost:4200/assets/test-loader.js:40:24)
    at http://localhost:4200/assets/test-support.js:5863:16: Could not find module yadda@ 1 ms
Source: 	
Error: Could not find module yadda
    at missingModule (http://localhost:4200/assets/vendor.js:125:11)
    at requireModule (http://localhost:4200/assets/vendor.js:135:17)
    at require (http://localhost:4200/assets/blanket-loader.js:128:16)
    at http://localhost:4200/assets/sf-todo.js:1201:23
    at mod.state (http://localhost:4200/assets/vendor.js:150:29)
    at tryFinally (http://localhost:4200/assets/vendor.js:30:14)
    at requireModule (http://localhost:4200/assets/vendor.js:148:5)
    at require (http://localhost:4200/assets/blanket-loader.js:128:16)
    at oldLoader (http://localhost:4200/assets/blanket-loader.js:84:13)
    at Object._blanket.extend.utils.processFile (http://localhost:4200/assets/test-support.js:12100:17)
```
Has anyone else seen this?  I have also opened curit/ember-cli-yadda#15 that has a bit more info.

### PR DESCRIPTION
**Pull request by jschilli**
*** FOR DISCUSSION *** 
will cleanup some of the logging but otherwise this is the new `wrapModules` approach that avoids touching `require`

dependent on 

https://github.com/alex-seville/blanket/pull/545
https://github.com/ember-cli/loader.js/pull/62

some open questions - will add inline

*** DO NOT MERGE ***

### CODE REVIEW

File: vendor/blanket-require.js [hunk 1]
```diff
@@ -89,18 +90,24 @@ if (blanket.options('enableCoverage')) {
...
-          try {
-            blanketLoader(moduleName);
-          } catch (err) {
-            console.log(err);
-          }
-        }
-      }
-    }
-  }
+  // if (blanket.options('enableCoverage')) {
```
Comment (jschilli) [inline vendor/blanket-require.js]: @sglanzer not sure if this is required anymore - can't find a suitable test case for it

in any case, as written it will no longer work (and suffers from the not everything is in requirejs.entries issue)

Comment (sglanzer) [inline vendor/blanket-require.js]: @jschilli The purpose of this was to report coverage (as 0%) on files that weren't part of the required files when running the app/tests - e.g. a util class that wasn't imported.  I'm not sure if that's handled, but it's such a low runner that I'm also not concerned if we don't handle it.

**Comment by sglanzer** [comment]
This is great - should protect us moving forward with ember-cli and fixes a number of the initial hacks done to make the integration work.  Thanks so much @jschilli

**Comment by rwjblue** [comment]
It seems that there is extremely little movement in Blanket lately, we may need to fork and publish a `ember-cli-blanket-blanket-fork` with the changes to be able to move forward...

**Comment by jschilli** [comment]
Agreed.

need to add some code to ensure that the right version of loader.js (bower and now npm)

it’s on my list but have been slammed.

**Comment by sglanzer** [comment]
Yeah, I was thinking the same thing...I don't like forking other people's projects, but I also really want to get this working with ember-cli 2.3 now that it's out of beta

**Comment by sglanzer** [comment]
We've also been considering moving to istanbul - would require a bit of re-coding, but likely much more stable moving forward

**Comment by jschilli** [comment]
@sglanzer not sure what's up with travis.  jshint passes here with version 2.5 and 2.6.3  - AFAIK there is no line 55 in lib/reporters/lcov.js

this last change I made is to check for minimum version of loader.js 3.6.1 (for bower) and then 4.0 (npm)

I'm using the tagger version of blanket @ my commit to such - may want to move that up or down.

I tested this on a 1.13 addon and a new 2.3 app project and got good results with both

Eyes on this from others would be appreciated

**Comment by jschilli** [comment]
investigating some lower coverage numbers with newest code - will advise

File: blueprints/ember-cli-blanket/index.js [hunk 2]
```diff
@@ -6,7 +6,7 @@ module.exports = {
   normalizeEntityName: function() {},
 
   afterInstall: function() {
-    return this.addBowerPackageToProject('blanket', '~1.1.5', {saveDev: true})
+    return this.addBowerPackageToProject('blanket', '#5e94fc30f2e694bb5c3718ddcbf60d467f4b4d26', {saveDev: true})
```
Comment (elwayman02) [inline blueprints/ember-cli-blanket/index.js]: You need to add `ember-cli-version-checker` to the blueprint

File: index.js [hunk 3]
```diff
@@ -14,6 +17,20 @@ function logErrors(err, req, res, next) {
...
+          bowerDep = checker.for('loader.js', 'bower'),
+          npmDep = checker.for('loader.js', 'npm');
+          debug('loader.js version (bower): ', bowerDep.version);
+          debug('loader.js version (npm): ', npmDep.version);
+      return (bowerDep.satisfies('>= 3.6.1') || npmDep.satisfies('>= 4.0.0'));
+  },
+
+  init: function() {
+    if (!this.checkDeps()) {
+        throw new Error('loader.js must be >= 3.6.0 (bower) or >= 4.0.0 (npm)');
```
Comment (elwayman02) [inline index.js]: This should say 3.6.1, should it not?

Comment (jschilli) [inline index.js]: yes, good catch

File: blueprints/ember-cli-blanket/index.js (hunk 2 above)
Comment (jschilli) [inline blueprints/ember-cli-blanket/index.js]: I've hashed through this a few times in my mind and with code.  In short, if you've installed this version of ember cli-blanket you need to have that version of blanket.js installed.  Full Stop.   There is no backward compatible integration with older versions of loader.js  we should consider this when changing the version number.

I have the code for the blueprint done but in practice ember cli calls init on addons as it collects them - that's where we are doing the version check so we emit an error and bomb out there well before you ever get to blueprint generation.

**Comment by jschilli** [comment]
@elwayman02 thanks for the eyes on this.  IMO we should finalize any questions and get this published.  It's been months now with a super variable blanket/ember-cli story.

cc: @sglanzer

**Comment by sglanzer** [comment]
Any README updates required and is this breaking due to loader.js or a minor bump?
